# cursor line
cursor-bg = "gray"
cursor-boldness = "bold"

# header lines
header-fg = "blue"
header-boldness = "non-bold"

# selected lines
selected-bg = "magenta"

# keybindings-help-menu-format = [ "key", "description" ]

[keybindings]
# "J" = { description = "Move cursor down 10 lines", operations = "cursor down 10" }
# "K" = { description = "Move cursor up 10 lines", operations = "cursor up 10" }
