# cursor line
cursor-bg = "blue"
cursor-boldness = "bold"

# header lines
header-fg = "blue"
header-boldness = "non-bold"

# selected lines
selected-bg = "magenta"

[keybindings]
"J" = [ "cursor down 10" ]
"K" = [ "cursor up 10" ]
