watched-command = "gdrive.py print-ui"
initial-env = [
  # TODO: watchbind should somehow handle these being unset at startup by itself
  'set-env pwd -- printf ""',
  'set-env total_size -- printf "unknown"',
]
interval = 1.0
header-lines = 3
field-separator = ","

[keybindings]
"J" = [ "cursor down 10" ]
"K" = [ "cursor up 10" ]
"x" = [ "exec -- gdrive.py delete", "reload", "unselect-all" ]

# "l" = [ "gdrive.py download &" ]
# "p" = [ "gdrive.py upload &" ]
# "u" = [ "gdrive.py space-used &" ]

# Traverse into a directory
"l" = [ "set-env pwd -- gdrive.py enter-dir", "reload" ]

# Traverse out of a directory
"h" = [ "set-env pwd -- gdrive.py exit-dir", "reload" ]

# Update $total_size (since it takes too long to execute periodically)
"s" = [ "set-env total_size -- gdrive.py total-size", "reload" ]
