command = "torrent.py list"
interval = 1
header-lines = 1
field-seperator = ","

[keybindings]
"p" = [ "torrent.py add", "reload" ]
"l" = [ "torrent.py start", "reload", "unselect-all" ]
"h" = [ "torrent.py stop", "reload", "unselect-all" ]
"x" = [ "torrent.py remove", "reload", "unselect-all" ]
"X" = [ "torrent.py delete", "reload", "unselect-all" ]
"f" = [ "torrent.py file", "reload", "unselect-all" ]
