watched-command = "torrent.py list"
interval = 1
header-lines = 1
field-separator = ","

[keybindings]
"p" = [ "exec -- torrent.py add", "reload" ]
"l" = [ "exec -- torrent.py start", "reload", "unselect-all" ]
"h" = [ "exec -- torrent.py stop", "reload", "unselect-all" ]
"x" = [ "exec -- torrent.py remove", "reload", "unselect-all" ]
"X" = [ "exec -- torrent.py delete", "reload", "unselect-all" ]
"f" = [ "exec -- torrent.py file", "reload", "unselect-all" ]
