[bell]
command = "None"
duration = 0

[cursor]
thickness = 0.25

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "Bitstream Vera Sans Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Bitstream Vera Sans Mono"
style = "Italic"

[font.normal]
family = "Bitstream Vera Sans Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors.toml"]
