#!/bin/sh

export PATH=$PATH:$HOME/.local/bin:$HOME/.cargo/bin
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="qutebrowser"

export SXHKD_SHELL=/bin/sh

# clipmenu
# export CM_LAUNCHER=rofi
# export CM_OUPUT_CLIP=0

# fzf
source ~/.config/fzf/config.sh
