#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
polybar.sh &
feh --no-fehbg --bg-scale ~/.config/wallpaper/wallpaper.jpg &

[ "$(theme.sh)" = "dark" ] && BORDER="#282c34" || BORDER="#ffffff"
FOCUSED_BORDER="#8FAAC9"
bspc config normal_border_color "$BORDER"
bspc config focused_border_color "$FOCUSED_BORDER"
bspc config border_width 2
bspc config window_gap 1

bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspwm-rule-floating.sh

bspc rule -a Zathura state=tiled focus=on desktop=any.!occupied
bspc rule -a discord desktop=any.!occupied
bspc rule -a mpv desktop=any.!occupied
bspc rule -a Slack desktop=any.!occupied
# bspc rule -a jetbrains-idea-ce desktop=any.!occupied
