#!/bin/sh

# === TOOLS
export TERMINAL="alacritty"
export EDITOR="nvim"
export BROWSER="qutebrowser"

# === LOCATIONS
export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export PATH=$PATH:$HOME/.local/bin:$HOME/.cargo/bin

# === TOOL-SPECIFIC
## wayland
export MOZ_ENABLE_WAYLAND=1

## chromium/firefox screensharing
export XDG_CURRENT_DESKTOP="sway"

## intellij
export _JAVA_AWT_WM_NONREPARENTING=1

## qutebrowser
# export QUTE_QT_WRAPPER="PyQt6"
# export QT_QPA_PLATFORM="wayland"

## fzf
source ~/.config/fzf/config.sh

## ssh
eval $(keychain --eval id_rsa)

## gdrive.py
export GDRIVE_UPLOADABLE_FILE_EXTENSIONS="-e mp4 -e mkv -e webm"
