#!/bin/sh

. $HOME/.config/zsh/profile

# === General

# Set background and border color
BORDER_FOCUSED="0x8faac9"
if [ "$(theme.sh)" = "dark" ]; then
    BORDER_NORMAL="0x282c34"
else
    BORDER_NORMAL="0xffffff"
fi
riverctl background-color 0x000000
riverctl border-color-focused "$BORDER_FOCUSED"
riverctl border-color-unfocused "$BORDER_NORMAL"


# === Keybindings

# exit river
riverctl map normal Super+Shift E exit

# reload river+waybar
riverctl map normal Super R spawn "~/.config/river/reload"

# open terminal
riverctl map normal Super Return spawn "$TERMINAL"

# open browser
riverctl map normal Super Backspace spawn "$BROWSER"

# close the focused view
riverctl map normal Super Q close

# focus the next/previous view in the layout stack
riverctl map normal Super Tab focus-view next
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# decrease/increase the main ratio of rivertile(1)
riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# tags (desktops/workspaces)
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


# === System controls

# change volume
riverctl map -repeat normal None XF86AudioRaiseVolume  spawn 'change-volume.sh up'
riverctl map -repeat normal None XF86AudioLowerVolume  spawn 'change-volume.sh down'
riverctl map -repeat normal None XF86AudioMute         spawn 'change-volume.sh mute'
riverctl map -repeat normal None XF86AudioMicMute      spawn 'change-volume.sh mic-mute'

# change screen brightness
riverctl map normal None XF86MonBrightnessUp   spawn 'change-brightness.sh up'
riverctl map normal None XF86MonBrightnessDown spawn 'change-brightness.sh down'

# close dunst notifications
riverctl map normal Super W       spawn 'dunstctl close'
riverctl map normal Super+Shift W spawn 'dunstctl close-all'

# take screenshot
# super + shift + {3, 4}
# 	screenshot.sh {_, select}
riverctl map normal Alt+Shift 3 spawn 'screenshot.sh'
riverctl map normal Alt+Shift 4 spawn 'screenshot.sh select'

# control media player
# riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
# riverctl map normal None XF86AudioPlay  spawn 'playerctl play-pause'
# riverctl map normal None XF86AudioPrev  spawn 'playerctl previous'
# riverctl map normal None XF86AudioNext  spawn 'playerctl next'


# === External Apps

# rofi power
riverctl map normal Super Escape spawn 'rofi-power.sh'

# rofi apps
riverctl map normal Super D spawn 'rofi -show drun -theme ~/.config/rofi/themes/icons-$(theme.sh).rasi'

# rofi script launcher
riverctl map normal Super S spawn 'rofi-scripts.sh'

# rofi clipboard
riverctl map normal Super P spawn 'clipboard.sh rofi'

# super + o
# 	rofi-calc.sh

# play media from clipboard in mpv
riverctl map normal Super Y       spawn 'mpv.sh'
riverctl map normal Super+Shift Y spawn 'mpv.sh background'


# === Keyboard

riverctl keyboard-layout \
	-variant altgr-intl \
	-options caps:swapescape,altwin:swap_lalt_lwin \
	us

riverctl set-repeat 25 200


# === Pointers

riverctl hide-cursor timeout 1500

# internal touchpad
trackpad="pointer-2-7-SynPS/2_Synaptics_TouchPad"
riverctl input "$trackpad" natural-scroll enabled
riverctl input "$trackpad" tap enabled
# riverctl input "$trackpad" pointer-accel 0.1

# internal trackpoint
trackpad="pointer-2-10-TPPS/2_IBM_TrackPoint"
riverctl input "$trackpad" natural-scroll enabled
# riverctl input "$trackpad" pointer-accel 0.1

# logitech m720 triathlon mouse
trackpad="pointer-1133-45077-M720_Triathlon_Mouse"
riverctl input "$trackpad" natural-scroll enabled
# riverctl input "$trackpad" tap enabled
# riverctl input "$trackpad" pointer-accel 0.1

# ---------------------------------------------------------


# TODO: external displays
# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100 riverctl map normal Super+Alt+Shift L resize horizontal 100 # Super + Left Mouse Button to move views riverctl map-pointer normal Super BTN_LEFT move-view Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Make all views with an app-id that starts with "float" and title "foo" start floating.
#riverctl rule-add float -app-id 'float*' -title 'foo'

# Make all views with app-id "bar" and any title use client-side decorations
#riverctl rule-add csd -app-id "bar"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile \
    -view-padding 2 \
    -outer-padding 1 &
